import { PageHeader } from "@/components/PageHeader";
import { ReportViewer } from "@/components/ReportViewer";
import { ErrorState } from "@/components/ErrorState";
import { useMetrics } from "@/hooks/useAnalysis";

export function Metrics() {
  const { data, isLoading, isError, refetch } = useMetrics();

  return (
    <div>
      <PageHeader
        eyebrow="AI Generated"
        title="Financial Metrics"
        description="Generated from the latest uploaded report"
      />

      {isError ? (
        <ErrorState onRetry={() => refetch()} />
      ) : (
        <ReportViewer
          title="Financial Metrics"
          markdown={data?.markdown}
          isLoading={isLoading}
          onRegenerate={() => refetch()}
          badge={{
            label: "Generated by AI",
            variant: "default",
          }}
        />
      )}
    </div>
  );
}
